---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "labels" . | indent 2 }}
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
    {{- include "labels" . | indent 4 }}
  template:
    metadata:
      labels:
      {{- include "labels" . | indent 6 }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}
        name: {{ .Chart.Name }}
        envFrom:
         - configMapRef:
                name: {{ .Values.configMap.name }}
