---
{{ $saName := .Values.serviceAccount.name }}
{{- with .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  labels:
    {{- range $.Values.serviceAccount.labels }}
    tier-{{ . }}: enforce
    {{- end }}
    {{- include "labels" . | indent 2 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ ( index $.Values.serviceAccount.annotations "eks.amazonaws.com/role-arn" ) }}
{{- end }}
