---
apiVersion: batch/v1
kind: Job
metadata:
  name: upgrade-hook
  annotations:
    "helm.sh/hooks": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: upgrade-hook
        image: alpine
        command: ["echo",  "I Made Some Actions After Upgrade"]
      restartPolicy: Never
  backoffLimit: 4
